### ISSUE TITLE
Function PKModelTwoCpt not found

### ISSUE THREAD

**Issue by yhwhu2008** [metrumresearchgroup/Torsten#1]
Hi, I am just starting with torsten and have a problem. I tried to run the twoCptModel example but got the following error. I can run simple stan code such as the 8school example. I can also find the PKModelTwoCpt.hpp file in the folder. But it just cannot compile. 

SYNTAX ERROR, MESSAGE(S) FROM PARSER:

No matches for: 

  PKModelTwoCpt(real[], real[], real[], real[], int[], int[], int[], int[], real[], real[], real[])

Function PKModelTwoCpt not found.
  error in 'model283c556e597_twoCptModel' at line 69, column 40
  -------------------------------------------------
    67:   // compartment at each event.
    68:   x = PKModelTwoCpt(time, amt, rate, ii, evid, cmt, addl, ss,
    69:                    theta, biovar, tlag);
                                               ^
    70: 
  -------------------------------------------------

Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'twoCptModel' due to the above error.
In addition: Warning message:
In readLines(file, warn = TRUE) :
  incomplete final line found on

**Comment by yizhang-cae** [comment]
Possibly `make` is not able to find torsten src.
How did you compile the model? What I do is 
```bash
make ../example-models/TwoCptModel/TwoCptModel
```
in `Torsten/cmdstan` path.

**Comment by yhwhu2008** [comment]
I installed rstan with torsten. How could I fix this problem in R?

**Comment by edvergsten** [comment]
I get the same error message as yhwhu2008 when installing rstan through torsten:

make: *** [stanc.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.3/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="rstan.dll" OBJECTS="chains.o init.o lang__ast_def.o lang__grammars__bare_type_grammar_inst.o lang__grammars__expression07_grammar_inst.o lang__grammars__expression_grammar_inst.o lang__grammars__functions_grammar_inst.o lang__grammars__indexes_grammar_inst.o lang__grammars__program_grammar_inst.o lang__grammars__semantic_actions.o lang__grammars__statement_2_grammar_inst.o lang__grammars__statement_grammar_inst.o lang__grammars__term_grammar_inst.o lang__grammars__var_deccls_grammar_inst.o lang__grammars__whitespace_grammar_inst.o misc.o sparse_extractors.o stanc.o"' had status 2
ERROR: compilation failed for package 'rstan'

BUT, on a different computer I get this error message:

C:/Users/username/Documents/R/win-library/3.5/StanHeaders/include/src/stan/lang/generator/generate_function_instantiation_body.hpp: In function 'void stan::lang::generate_function_instantiation_body(const stan::lang::function_decl_def&, const std::vector<std::basic_string<char> >&, bool, bool, bool, const string&, std::ostream&)':
C:/Users/username/Documents/R/win-library/3.5/StanHeaders/include/src/stan/lang/generator/generate_function_instantiation_body.hpp:44:45: error: range-based 'for' loops are not allowed in C++98 mode
       for (const std::string& namespace_i : namespaces) {
                                             ^
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: stanc.o] Error 1
ERROR: compilation failed for package 'rstan'

This might be a separate question, but could this have something to do with this sentence from README.md?
"Please ensure CXXFLAGS in .R/Makevars constains flag -std=c++11."
I don't know how to do this. Am I editing a file or is this performed in R?

**Comment by edvergsten** [comment]
I've solved my own problem with installing torsten. For someone with very little C++ knowledge, this was very confusing.

I had to edit 2 files. Both are called "Makeconf" and located in
Program Files\R\R-3.5.1\etc\i386
and
Program Files\R\R-3.5.1\etc\x64.

Change
CXXFLAGS = -O2 -Wall  $(DEBUGFLAG)
to
CXXFLAGS = -O2 -Wall -std=c++11 $(DEBUGFLAG)
in both Makeconf files.
Then re-run install_torsten() in R.

Consider adding this info to the readme.
