### ISSUE TITLE
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version[BUG] 

### ISSUE THREAD

**Issue by Thala1985** [metrumresearchgroup/Torsten#12]
## Description
Executing source(install.R) from R console to install torsten resulted with SSL error.
Our SUSE 11.4 does not support this due to outdated version may be.

## Example
> source('install.R')
Loading required package: usethis
Loading torstenHeaders
Error in open.connection(x, "rb") :
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
>

The above error is reported while trying to install. by checking the files inside the TorstenHeaders folder, noticed that https://github.com are used in the script. 

Just manually trying to call this site result same error.

wget https://github.com/metrumresearchgroup/TorstenHeaders/tree/master/inst
--2019-09-04 11:44:11--  https://github.com/metrumresearchgroup/TorstenHeaders/tree/master/inst
Resolving github.com... 140.82.118.3
Connecting to github.com|140.82.118.3|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

## Expected Output
Other site, example CRAN works well.

wget http://cran.r-project.org/web/packages/
--2019-09-04 11:44:49--  http://cran.r-project.org/web/packages/
Resolving cran.r-project.org... 137.208.57.37
Connecting to cran.r-project.org|137.208.57.37|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3070 (3.0K) [text/html]
Saving to: `index.html'

100%[===============================================================================================>] 3,070       --.-K/s   in 0s

2019-09-04 11:44:50 (118 MB/s) - `index.html' saved [3070/3070].

Troubleshooting:
We have upgraded to openssl version to latest 1.1.1c & git 2.9.5

Can you kindly let us know what binary needs upgrade OR please provide an offline installation package

#### Current Version:
v0.87.1

**Comment by yizhang-yiz** [comment]
SUSE 11.4 is fairly ancient. Could you update wget to slightly improve the chance?

`cmdstan` is actually included in the repo, so that one can actually compile and run a Torsten/Stan script without R.

**Comment by Thala1985** [comment]
Thanks for the response. I am not familiar with other compilation.
But i got SuSe 12 now and the installation of the script install.R was smooth.

I ran the uni Test provided here, which resulted a failure.
Please let me know if you need full error details.
.

> /stan/math/rev/mat/functor/adj_jac_apply.hpp:31:32: error: ‘std::index_sequence’ has not been declared
>                            std::index_sequence<I...> i) {

**Comment by yizhang-yiz** [comment]
Did you invoke CXX14 in `.R/Makevars` as shown in https://github.com/metrumresearchgroup/Torsten/blob/master/README.md#r-interface?
