### ISSUE TITLE
Installation error:   version '2.18.1.10' is invalid for package 'StanHeaders'

### ISSUE THREAD

**Issue by ayeerr** [metrumresearchgroup/Torsten#19]
All,

I am trying to torsten within a docker image on an AWS ubuntu instance. I am getting an error regarding download issues for 'StanHeader'. Seems like version "2.18.1.10" is explicitly mentioned during installation. 2.18.1.10 seems to be a perfectly valid version for StanHeaders. 

Not sure what is going on. 

Thanks
ayeerr

> install_torsten()
Error in download_version_url(package, version, repos, type) : 
  version '2.18.1.10' is invalid for package 'StanHeaders'
Calls: source ... install_torsten -> <Anonymous> -> <Anonymous> -> download_version_url
Execution halted
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `lib`

**Comment by yizhang-yiz** [comment]
Thanks for reporting. I've updated master to v0.87.2. Could you give another try?

**Comment by ayeerr** [comment]
Thanks yizhang, 

We can close this issue

Thanks
ayeerr
