### ISSUE TITLE
Change in README to link MPICH installation page[DOC]

### ISSUE THREAD

**Issue by csetraynor** [metrumresearchgroup/Torsten#22]
## Description
The first look into MPI might be a bit challenging.

## Expected documentation
I found this tutorial https://mpitutorial.com/tutorials/ very enlightening.

I would recommend to link in README the MPICH download page.
https://www.mpich.org/downloads/

#### Current Version:
v0.87.1

**Comment by yizhang-yiz** [comment]
> I found this tutorial https://mpitutorial.com/tutorials/ very enlightening.

From Stan/Torsten user's perspective learning MPI programming is not very rewarding unless he/she intends to contribute that part of code.

> I would recommend to link in README the MPICH download page.
https://www.mpich.org/downloads/

Good point. I'll address it right away.

**Comment by yizhang-yiz** [comment]
Addressed in https://github.com/metrumresearchgroup/Torsten/pull/23
