### ISSUE TITLE
[BUG] installation issues

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/Torsten#27]
I am trying to install  Torsten on macOS Mojave system version 10.14.6. I am using R version 3.6.3 and rstan_2.21.2.

 After downloading the folder from:  
https://github.com/metrumresearchgroup/Torsten

I also tried to install Torsten by running R script “install_torsten”  found in folder downloaded from https://github.com/metrumresearchgroup/TorstenHeaders 
but now success and got following massages

> library(rstan)
> library(devtools)
> devtools::load_all('TorstenHeaders')
Error in normalizePath(path, winslash = "/", mustWork = TRUE) : 
  path[1]="TorstenHeaders": No such file or directory
> install_torsten()
 Error in find.package("torstenHeaders") : 
  there is no package called ‘torstenHeaders’ 

I would be grateful if you give me some instruction on how to successfully install Torsten.

Best redards

**Comment by yizhang-yiz** [comment]
We're in the middle of switching from rstan to cmdstanr as our R interface. You can follow instruction [here](https://github.com/metrumresearchgroup/Torsten/blob/master/README.md) to use [cmdstanr](https://mc-stan.org/cmdstanr/articles/cmdstanr.html) with the latest release candidate. On the other hand, v0.87.2 is the last version with rstan. You can access it by
```bash
git clone -b torsten_v0.87.2 git@github.com:metrumresearchgroup/Torsten.git
```

**Comment by melagha** [comment]
Thank you for your prompted response. 
I have installed the cmdstanr and run the example provided with package : 
https://mc-stan.org/cmdstanr/articles/cmdstanr.html

"file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file)"

However, when I tried to run different examples provided in the same package or examples from torsten package I receive the following error:

Error in .subset2(public_bind_env, "initialize")(...) : 
  Assertion on 'stan_file' failed: File does not exist: '/Users/mg/.cmdstanr/cmdstan-2.25.0/examples/radon/radon.stan'.

I really appreciate your help and time.

regards,

**Comment by yizhang-yiz** [comment]
Looks like cmdstan couldn’t locate radon model. Could you double check the path?
  
  

  
  
>

**Comment by melagha** [comment]
It is 

"/Users/mg/.cmdstanr/cmdstan-2.25.0"

**Comment by melagha** [comment]
Sorry,
The file for the radon model is 
setwd("~/Desktop/Torsten-master-2/cmdstan/examples/radon”)
Actually the same file where the bernoulli.stan located .

**Comment by yizhang-yiz** [comment]
I don’t think cmdstanr comes with radon model. Please follow cmdstanr tutorial to use “set_cmdstan_path” to pick Torsten’s cmdstan. Note that Torsten ships its own customized cmdstan, which is different from cmdstanr would install.
  
  

  
  
>

**Comment by yizhang-yiz** [comment]
@melagha were you able to compile and run `radon` model? Let me know if you have any questions.

**Comment by melagha** [comment]
Thank you for the follow up.

Unfortunately I still not been able to run it.  Please see below the  log of my run and results: 


> check_cmdstan_toolchain()
The CmdStan toolchain is setup properly!
> cmdstan_path()
[1] "/Users/mg/Desktop/Torsten-master/example-models/pk2cpt/../../cmdstan"
> file <- file.path(cmdstan_path(), "example-models", "pk2cpt", "pk2cpt.stan")
> mod <- cmdstan_model(file)
Error in .subset2(public_bind_env, "initialize")(...) : 
  Assertion on 'stan_file' failed: File does not exist: '/Users/mg/Desktop/Torsten-master/example-models/pk2cpt/../../cmdstan/example-models/pk2cpt/pk2cpt.stan'



Best regards

**Comment by melagha** [comment]
Please ignore previous post. Following is the log of the run.

> library("cmdstanr")
> set_cmdstan_path("~/Desktop/Torsten-master/cmdstan")
CmdStan path set to: /Users/mg/Desktop/Torsten-master/cmdstan
> file.dir <- file.path("Torsten", "example-models", "pk2cpt")
> file  <- file.path(file.dir, "pk2cpt.stan")
> model <- cmdstan_model(file)
Error in .subset2(public_bind_env, "initialize")(...) : 
  Assertion on 'stan_file' failed: File does not exist: 'Torsten/example-models/pk2cpt/pk2cpt.stan'.
>

**Comment by yizhang-yiz** [comment]
By
```r
file.dir <- file.path("Torsten", "example-models", "pk2cpt")
 file  <- file.path(file.dir, "pk2cpt.stan")
```
you are asking for "Torsten/example-models/pk2cpt/pk2cpt.stan" at your current working directory. Please see if the following works
```r
file <- file.path(cmdstan_path(), "..", "example-models", "pk2cpt", "pk2cpt.stan")
model <- cmdstan_model(file)
```

**Comment by melagha** [comment]
It worked. I really appreciate your time and help.

Best regard

**Comment by yizhang-yiz** [comment]
Great. I'm closing this one.
