### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by DuyTran16** [metrumresearchgroup/Torsten#3]
Refer from original issue message <https://github.com/metrumresearchgroup/Torsten/issues/2>

I had to reinstall Torsten on a different computer (windows 10). The Makevars file were uncommented in skeleton folder in RcppArmadillo and RcppEigen packages so that
`CXX_STD = CXX11`

However installation problems similar to above except the following error message

> make: *** [C:/PROGRA~1/R/R-35~1.0/etc/x64/Makeconf:215: stanc.o] Error 1
> ERROR: compilation failed for package 'rstan'

Can you help me figure out what could be the problem?

**Comment by yizhang-cae** [comment]
I'm closing this since it's been resolved through a different channel.
