### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/Torsten#31]
Hello,
It is me again with the same error encountered the running 
“ GenTwoCptModel.stan”  and  “LinTwoCptModel.stan"

Hello it is me again with the same error encountered the running 
 Semantic error in “ GenTwoCptModel.stan” and “LinTwoCptModel.stan"

 '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb794415be.stan', line 106, column 7 to line 109, column 43:
   -------------------------------------------------
   104:  //                          1e-8, 1e-8, 1e8);
   105:  
   106:     x = generalOdeModel_rk45(twoCptModelODE, 3,
                ^
   107:                             time, amt, rate, ii, evid, cmt, addl, ss,
   108:                             theta, biovar, tlag,
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'generalOdeModel_rk45' was supplied.

Semantic error in '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb794415be.stan', line 106, column 7 to line 109, column 43:
   -------------------------------------------------
   104:  //                          1e-8, 1e-8, 1e8);
   105:  
   106:     x = generalOdeModel_rk45(twoCptModelODE, 3,
                ^
   107:                             time, amt, rate, ii, evid, cmt, addl, ss,
   108:                             theta, biovar, tlag,
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'generalOdeModel_rk45' was supplied.

make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb794415be.hpp] Error 1
make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb794415be.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.

Semantic error in '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb4f99fc66.stan', line 68, column 6 to line 69, column 34:
   -------------------------------------------------
    66:    // contains the biovariability fraction and the lag time of each compartment,
    67:    // and the NONMEM data.
    68:    x = linOdeModel(time, amt, rate, ii, evid, cmt, addl, ss,
               ^
    69:                    K, biovar, tlag);
    70:    cHat = col(x, 2) ./ V1;
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'linOdeModel' was supplied.

make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb4f99fc66.hpp] Error 1

Semantic error in '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb4f99fc66.stan', line 68, column 6 to line 69, column 34:
   -------------------------------------------------
    66:    // contains the biovariability fraction and the lag time of each compartment,
    67:    // and the NONMEM data.
    68:    x = linOdeModel(time, amt, rate, ii, evid, cmt, addl, ss,
               ^
    69:                    K, biovar, tlag);
    70:    cHat = col(x, 2) ./ V1;
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'linOdeModel' was supplied.

make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb4f99fc66.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.
> 

Semantic error in '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb689b55e.stan', line 106, column 7 to line 109, column 43:
   -------------------------------------------------
   104:  //                          1e-8, 1e-8, 1e8);
   105:  
   106:     x = generalOdeModel_rk45(twoCptModelODE, 3,
                ^
   107:                             time, amt, rate, ii, evid, cmt, addl, ss,
   108:                             theta, biovar, tlag,
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'generalOdeModel_rk45' was supplied.

Semantic error in '/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb689b55e.stan', line 106, column 7 to line 109, column 43:
   -------------------------------------------------
   104:  //                          1e-8, 1e-8, 1e8);
   105:  
   106:     x = generalOdeModel_rk45(twoCptModelODE, 3,
                ^
   107:                             time, amt, rate, ii, evid, cmt, addl, ss,
   108:                             theta, biovar, tlag,
   -------------------------------------------------

A returning function was expected but an undeclared identifier 'generalOdeModel_rk45' was supplied.

make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb689b55e.hpp] Error 1
make: *** [/var/folders/bd/xq4sxv9j3bl_j6rt1hggt3ch0000gn/T/Rtmpp29l70/model-31fb689b55e.hpp] Error 1
Error: An error occured during compilation! See the message above for more information.
>

**Comment by yizhang-yiz** [comment]
The two models you are looking for have been updated recently and I just merged them to master. You can re-download the repo and use model
https://github.com/metrumresearchgroup/Torsten/tree/master/example-models/pk2cpt_ode
and
https://github.com/metrumresearchgroup/Torsten/tree/master/example-models/pk3cpt_linode

**Comment by melagha** [comment]
I run them and both worked! 
Best regards.

**Comment by yizhang-yiz** [comment]
We're updating all the testing examples due to recent interface change. There might be other models failing to build but should be resolved soon.
