### ISSUE TITLE
posterior predictive distributions code

### ISSUE THREAD

**Issue by melagha** [metrumresearchgroup/Torsten#33]
I have fit a number of Torsten  population  models  with different residual variability options and the diagnostics look ok. However I did not find any code that I can use to extract posterior distributions and plot individual and population prediction to further evaluate the fit and guide model selection.
 
I am new Stan user and would appreciate any help.

Best regards

**Comment by yizhang-yiz** [comment]
[User guide](https://github.com/metrumresearchgroup/Torsten/blob/develop/docs/torsten_users_guide.pdf) sec. 4.9 shows a population PKPD model and you can find some [postprocessing script](https://github.com/metrumresearchgroup/Torsten/blob/develop/example-models/effCpt/run.R) here. In the script we use [posterior package](https://github.com/stan-dev/posterior) for operating on draws and [bayesplot package](https://mc-stan.org/bayesplot/index.html) for plotting.

There are many paths for model selection. One option that many Stan users choose is [loo package](http://mc-stan.org/loo/index.html). Depends on the outcome of the comparison, there's also an option of [model averaging & stacking](https://cran.r-project.org/web/packages/loo/vignettes/loo2-weights.html). These packages and methods are not currently incorporated in Torsten. Hopefully we'll be able to address that soon.

**Comment by melagha** [comment]
I am very grateful for your prompt very helpful  reply.

Regards
