### ISSUE TITLE
cmdstanr cannot load Torsten path from the user guide

### ISSUE THREAD

**Issue by cleonowens** [metrumresearchgroup/Torsten#39]
I have attempted to install Torsten, but I am having trouble. Can you please help?

I have successfully installed cmdstan:
`cmdstan_path()`
[1] "C:/Users/Cathrine Leonowens/Documents/.cmdstan/cmdstan-2.29.2"

`check_cmdstan_toolchain()`
The C++ toolchain required for CmdStan is setup properly!

And RStan is correctly installed (tested using the code here: [)](https://gist.github.com/rasmusab/744410db9cf85ecb85e1)

When I run the following code from your installation instructions [():](https://metrumresearchgroup.github.io/Torsten/installation/)
`cmdstanr::set_cmdstan_path("Torsten/cmdstan")`
I get the following error:
Warning message:
Path not set. Can't find directory: Torsten/cmdstan 

When I re-check the path for cmdstan, I get the correct  path:
`cmdstan_path()`
[1] "C:/Users/Cathrine Leonowens/Documents/.cmdstan/cmdstan-2.29.2"

#### Current Version:
R: 4.1.3
RStudio: 2022.02.1 Build 461, "Prairie Trillium" Release (8aaa5d47, 2022-03-17) for Windows
cmdstan:2.29.2
Rstan: 2.21.0
rtools: 4.0.3.0

Am I missing a step?

**Comment by yizhang-yiz** [comment]
Sorry that the installation instruction is clear enough. I'll update it soon.

Please do the following.
1. Download Torsten from [here](https://github.com/metrumresearchgroup/Torsten/archive/refs/heads/master.zip).
2. Unpack the downloaded file to, let's say, `workpath/Torsten`
3. In R, do `cmdstanr::set_cmdstan_path("workpath/Torsten/cmdstan")`
4. In R, do `cmdstanr::rebuild_comstanr()`
5. In R, try to build a test model such as `model <- cmdstan_model("workpath/Torsten/example-models/pk2cpt_ode/pk2cpt_ode.stan")`

Finishing step 5 would indicate Torsten is successfully set up.

**Comment by cleonowens** [comment]
Hi, Yi. I see you closed the ticket but I still have this question: Does workpath/Torsten have to be in a sub folder in the one found with cmdstan_path()?

Cathrine
Cathrine Leonowens
Mobile 303.653.5411
"Think higher, feel deeper" - Elie Wiesel

**Comment by yizhang-yiz** [comment]
@cleonowens `workpath/Torsten/` can be anywhere as long as you can write to that path. Regardless of the current value of `cmdstan_path`, you can always use ``set_cmdstan_path` to let `cmdstanr` konw where that path `workpath/Torsten` is.

Let me know if this helps. Thanks.

**Comment by cleonowens** [comment]
Thank you! Does workpath/Torsten have to be in a sub folder in the one found with cmdstan_path()?

Cathrine
Cathrine Leonowens
Mobile 303.653.5411
"Think higher, feel deeper" - Elie Wiesel

**Comment by yizhang-yiz** [comment]
> Thank you! Does workpath/Torsten have to be in a sub folder in the one found with cmdstan_path()?

No it doesn't.
