### ISSUE TITLE
[DOC] twocpt_population is not a hierarchical population model

### ISSUE THREAD

**Issue by billgillespie** [metrumresearchgroup/Torsten#43]
## Description
The twocpt_population model in the example-models directory is not an appropriately constructed population model, i.e., a hierarchical model with inter-individual variability in model parameters. It is instead a simultaneous fit of a set of individual models---one model per individual. While this is suitable for demonstrating the use of the `pmx_solve_group` functions, it does not demonstrate good PK modeling practice. The model should be replaced by a correctly structured model.

## Expected documentation
Revise or replace twocpt_population with a corrected model. This also needs to be changed in the Users Guide.

#### Current Version:
v0.90.0

**Comment by yizhang-yiz** [comment]
I can do this during the holiday break.
