### ISSUE TITLE
[BUG] bioavailability calculation error on MacOS with LLVM 15

### ISSUE THREAD

**Issue by yizhang-yiz** [metrumresearchgroup/Torsten#50]
## Description
From a user report I was able to trace the error to bioavailability calculation at

https://github.com/metrumresearchgroup/Torsten/blob/2d9076fe99a2f6dfc1ed0d40657fcc3e438a306d/cmdstan/stan/lib/stan_math/stan/math/torsten/ev_manager.hpp#L251

## Example
- build pk2cpt example with llvm 15 toolchain
- the pk2cpt will sample with initialization error.

## Expected Output
Pass all tests and example models run w/o issue.

#### Current Version:
v0.89.0

**Comment by yizhang-yiz** [comment]
Thanks for reporting. This has been noticed and currently under investigation. See
https://github.com/metrumresearchgroup/Torsten/issues/50

We've found that the issue only occurs on MacOS using llvm 15+, so most likely Ventura & Sonoma are generally affected. Before I can fix it the only solution would be to use older version llvm.

**Comment by yizhang-yiz** [comment]
@billgillespie could you check if https://github.com/metrumresearchgroup/Torsten/tree/v0.91.0rc3 fixes the MacOS issue? Thanks.

**Comment by billgillespie** [comment]
@yizhang-yiz, The pk2cpt ran successfully with v0.91.0rc3 using clang 15.0.0 on my MacBook Air running macOS 14.3.1...

**Comment by yizhang-yiz** [comment]
@jburos, could you give another try of the release candidate https://github.com/metrumresearchgroup/Torsten/tree/v0.91.0rc3 ? Thanks.

**Comment by jburos** [comment]
> @jburos, could you give another try of the release candidate https://github.com/metrumresearchgroup/Torsten/tree/v0.91.0rc3 ? Thanks.

Hi @yizhang-yiz, thanks so much for fixing this. Both this example and one of my own work perfectly on my M3 mac computer, using the standard LLVM+clang setup.

**Comment by yizhang-yiz** [comment]
Thanks @jburos !
