### ISSUE TITLE
user guide: undocumented top-level functions

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/Torsten#57]
The following top-level functions are not documented in `docs/torsten_users_guide.org` (as of b414a05ac4, current tip of `develop`):

 * `pmx_ode_adams`
 * `pmx_ode_adams_ctrl`
 * `pmx_ode_bdf`
 * `pmx_ode_bdf_ctrl`
 * `pmx_ode_ckrk`
 * `pmx_ode_ckrk_ctrl`
 * `pmx_ode_rk45`
 * `pmx_ode_rk45_ctrl`
 * `pmx_solve_onecpt_effcpt`
 * `pmx_solve_twocpt_effcpt`

**Comment by yizhang-yiz** [comment]
This is addressed in #64 .
